name:                rpe-program
version:             0.1.0.0
github:              githubuser/rpe-program
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2018 Author name here

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/rpe-program#readme>

dependencies:
- base >= 4.10 && < 10
- file-embed
- lucid
- rio >= 0.1.1.0
- yaml

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  rpe-program:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - rpe-program
    - optparse-simple

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
